# Generated by Django 5.0.1 on 2024-07-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, unique=True)),
                ('parol', models.CharField(max_length=128)),
                ('email', models.CharField(max_length=150, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
