# Generated by Django 5.0.1 on 2024-07-11 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudtech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybase',
            name='email',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='mybase',
            name='login',
            field=models.CharField(max_length=100),
        ),
    ]
